import { existsSync } from "node:fs";
import { loadEnvFile } from "node:process";
import { resolve } from "node:path";

export function resolveConfigFile(
  configuredPath = process.env.RONIX_CONFIG,
  cwd = process.cwd(),
): string {
  return resolve(cwd, configuredPath?.trim() || ".env");
}

export function loadConfigFile(
  configuredPath = process.env.RONIX_CONFIG,
  cwd = process.cwd(),
): string {
  const path = resolveConfigFile(configuredPath, cwd);
  if (existsSync(path)) {
    loadEnvFile(path);
  } else if (configuredPath) {
    throw new Error(`RONIX_CONFIG does not exist: ${path}`);
  }
  return path;
}

export function parseEnvFile(content: string): Record<string, string> {
  const values: Record<string, string> = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const separator = line.indexOf("=");
    if (separator <= 0) continue;
    const key = line.slice(0, separator).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
    values[key] = unquote(line.slice(separator + 1).trim());
  }
  return values;
}

export function serializeEnvFile(
  entries: ReadonlyArray<readonly [string, string]>,
): string {
  return [
    "# Generated by Ronix setup. Run `npm run setup` to update it.",
    ...entries.map(([key, value]) => `${key}=${quote(value)}`),
    "",
  ].join("\n");
}

function quote(value: string): string {
  if (/^[A-Za-z0-9_./,:@%+-]*$/.test(value)) return value;
  return JSON.stringify(value);
}

function unquote(value: string): string {
  if (value.startsWith("\"") && value.endsWith("\"")) {
    try {
      return JSON.parse(value) as string;
    } catch {
      return value.slice(1, -1);
    }
  }
  if (value.startsWith("'") && value.endsWith("'")) {
    return value.slice(1, -1);
  }
  return value;
}
